db:
  connection: '{connectionString: ''http://___'', userName: ''horijon'', password:''pass''}'
  host: 127.0.0.1
  port: 1200
dbValues: '{connectionString: ''http://___'', userName: ''horijon'', password: ''pass''}'
management:
  endpoints:
    web:
      exposure:
        include: '*'
my:
  greeting: Hello Test Profile, running on a different port i.e. 8700
  list:
    values: One,Two,Three,Four,Five
server:
  port: 8700
spring:
  profiles:
    active: test